include "default-core"
include "default-http"
include "default-rpc3"

http {
  routes {
    ask-timeout = 15s
  }

  port=8080  
  uri="/api/v1/rpc3"
}

api.key="${IKA_API_KEY}"

akka.http.server.parsing.illegal-header-warnings = off
akka.http.parsing.max-chunk-size = 10m


# --- Solana ---------------------------------------------------------------------------------------

rpc_solana {
  type="rpc3://"
  chain="solana"
  strategy="cache_async"
  ttl=30000
  latest=500
  gc=8000
}

pool_solana {
  type="pool://"
  strategy="sticky"
  destinations = [
    ${SOL_RPC_URL}
  ]
}

# --- EVM ------------------------------------------------------------------------------------------

rpc_evm {
  type="rpc3://"
  chain="evm"
  strategy="cache_async"
  ttl=25000
  latest=12000
  gc=15000
}

pool_evm {
  type="pool://"
  strategy="sticky"
  destinations = [
    ${ETH_RPC_URL}
  ]
}

# ---------------------------------------------------------------------------------------------------

retry_3 {
  type="retry://"
  maxRetries=3
  delay=1000
}

http_client {
  type="http://"
  compression="deflate,gzip"
  connectTimeout=3000
  responseTimeout=13000
}

# ===================================================================================================

profiles {
  solana = {
    processors = "rpc_solana, pool_solana, retry_3, http_client"
  }

  evm = {
    processors = "rpc_evm, pool_evm, retry_3, http_client"
  }
}

#telemetry = "stdout://1000?format=csv"
telemetry = "log://60000"